version: "2"

services:
  postgresql:
    container_name: postgres
    restart: always
    image: postgres:14.0
    environment:
      - POSTGRES_USER=bindplane
      - POSTGRES_PASSWORD=bindplane
      - POSTGRES_DB=bindplane
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  prometheus:
    container_name: prometheus
    restart: always
    image: prom/prometheus:v2.47.2
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=2d'
      - '--web.enable-remote-write-receiver'
      - '--web.listen-address=0.0.0.0:9090'
      - '--storage.tsdb.path=/var/lib/prometheus/tsdb'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/rules.yml:/etc/prometheus/rules.yml
      - ./data/prometheus:/var/lib/prometheus/tsdb

  transform:
    container_name: transform-agent
    restart: always
    image: ghcr.io/observiq/bindplane-transform-agent:latest

  # When BindPlane is operating in distributed mode, it must
  # be configured with the following:
  # - A distributed event bus (NATS)
  # - An external data store (Postgres)
  # - An external time series database (Prometheus)
  # - An external transform agent (Transform Agent)
  # - A load balancer
  # - The remote url (BINDPLANE_REMOTE_URL) must be set to the
  #   load balancer url or internal docker service name. This allows
  #   agents to connect to BindPlane and forward measurement data.
  #   NOTE: Agents outside of this docker context will not be able to
  #   connect because they cannot resolve the "bindplane" service.
  bindplane:
    restart: always
    deploy:
      # The NGINX configuration expects five bindplane servers
      # with the names: bindplane-bindplane-1, bindplane-bindplane-2, etc.
      # Do not change the replica count without modifying the NGINX configuration.
      # Simiarly, the hostname "bindplane-bindplane-1" is derived from the compose
      # directory name and the bindplane service name.
      replicas: 5
    #image: ghcr.io/observiq/bindplane-ee:1.39.0
    image: observiq/bindplane-ee-amd64:latest
    environment:
      - BINDPLANE_USERNAME=admin
      - BINDPLANE_PASSWORD=password
      - BINDPLANE_REMOTE_URL=http://bindplane:3001
      - BINDPLANE_SESSIONS_SECRET=403dd8ff-72a9-4401-9a66-e54b37d6e0ce
      - BINDPLANE_LOG_OUTPUT=stdout
      - BINDPLANE_ACCEPT_EULA=true
      - BINDPLANE_LICENSE=${BINDPLANE_LICENSE}
      - BINDPLANE_SECRET_KEY=403dd8ff-72a9-4401-9a66-e54b37d6e0ce
      - BINDPLANE_TRANSFORM_AGENT_ENABLE_REMOTE=true
      - BINDPLANE_TRANSFORM_AGENT_REMOTE_AGENTS=transform:4568
      
      # Nats event bus
      - BINDPLANE_EVENT_BUS_TYPE=nats

      # Nats server
      - BINDPLANE_NATS_SERVER_ENABLE=true
      - BINDPLANE_NATS_SERVER_CLIENT_HOST=127.0.0.1
      - BINDPLANE_NATS_SERVER_CLIENT_PORT=4222
      - BINDPLANE_NATS_SERVER_HTTP_HOST=0.0.0.0
      - BINDPLANE_NATS_SERVER_HTTP_PORT=8222
      - BINDPLANE_NATS_SERVER_CLUSTER_NAME=bindplane-cluster
      - BINDPLANE_NATS_SERVER_CLUSTER_HOST=0.0.0.0
      - BINDPLANE_NATS_SERVER_CLUSTER_PORT=6222
      - BINDPLANE_NATS_SERVER_CLUSTER_ROUTES=nats://bindplane-bindplane-1:6222

      - BINDPLANE_PROMETHEUS_ENABLE_REMOTE=true
      - BINDPLANE_PROMETHEUS_HOST=prometheus
      - BINDPLANE_PROMETHEUS_PORT=9090
      - BINDPLANE_STORE_TYPE=postgres
      - BINDPLANE_POSTGRES_HOST=postgresql
      - BINDPLANE_POSTGRES_PORT=5432
      - BINDPLANE_POSTGRES_USERNAME=bindplane
      - BINDPLANE_POSTGRES_PASSWORD=bindplane
      - BINDPLANE_POSTGRES_DATABASE=bindplane
    depends_on:
      - postgresql

  # The BindPlane Agent is used to collect telemetry from a host.
  # It connects to BindPlane using OpAMP by targeting the docker
  # bindplane service.
  agent:
    deploy:
      replicas: 1
    image: observiq/bindplane-agent:1.42.0
    environment:
      - OPAMP_ENDPOINT=ws://bindplane:3001/v1/opamp
      - OPAMP_SECRET_KEY=403dd8ff-72a9-4401-9a66-e54b37d6e0ce
      - OPAMP_LABELS=configuration=test
    restart: always
    depends_on:
      - bindplane

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    # NGINX backend config is not robust in this example,
    # so make sure it starts last.
    depends_on:
      - bindplane
      - agent
